In [45]:
#Connecting to the database
import sqlite3
from tkinter import messagebox
from tkinter import *
# from tkinter.ttk import *
from tkinter import filedialog

myConnection = sqlite3.connect("database.db")
# connecting the connection to the database

root = Tk()
root.title("Job Application")
root.geometry("700x800")

def Add_data():
    f_name = fname.get()
    l_name = lname.get()
    E_mail = mail.get()
    my_education = varList.get()
    Add_1 = adr1.get()
    City = adr2.get()
    State = adr3.get()
    ZipCode = adr4.get()
    phone1 = ph1.get()
    phone2 = ph2.get()
    Hobby = hobby.get()
    CompanyName = cname1.get()
    JobTitle = job.get()
    TimeGap = timehere.get()
    RName1 = rn1.get()
    phone1 = rp1.get()
    Rname2 = rn2.get()
    phone2 = rp2.get()

    db = sqlite3.connect("database.db")
    c= db.cursor()

    c.execute('CREATE TABLE IF NOT EXISTS Data(id INT primary key,lname TEXT,mail TEXT,varList TEXT,college TEXT,adr TEXT,adr1 TEXT,adr2 TEXT,adr3 TEXT,adr4 INT,ph1 TEXT,ph2 INT,hobby TEXT,cname1 TEXT,job TEXT,timehere INT,rn1 TEXT,rp1 INT,rn2 TEXT,rp2 INT)')
    c.execute('INSERT INTO Data(fname,lname,mail,lst,adr1,college,adr2,adr3,adr4,ph1,ph2,hobby,cname1,job,timehere,rn1,rp1,rn2,rp2) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(f_name,l_name,E_mail,my_education,college,Add_1,City,State,ZipCode,phone1,phone2,Hobby,CompanyName,JobTitle,TimeGap,RName1,phone1,Rname2,phone2))
    db.commit()
    msg = Messagebox.showinfo("Application successfully submited")

c1 = Canvas(root, bg="brown", height = 10,width=700)
c1.place(x=0,y=0)
r = c1.create_polygon(0,0,10,700, fill="brown")
job_app = Label(root, text = "Job Application",font="segoe 30",padx=200) 
job_app.place(x=10,y=20)
personal_info = Label(root, text = "Personal Information",font = "segoe 15",fg="red")
personal_info.place(y=70)

name = Label(root, text = "Name:",font = "segoe 15")
name.place(y=100)
fname = Entry(root,width = 30)
fname.place(x=300,y=107)
fname.insert(0,"First Name")
lname = Entry(root,width = 30)
lname.place(x=500,y=107)
lname.insert(0,"Last Name")

email = Label(root, text = "Email:", font = "segoe 15")
email.place(y=130)
mail = Entry(root,width = 60)
mail.place(x=300,y=137)
mail.insert(0,"user@example.com")

edu = Label(root, text = "Education:", font = "segoe 15")
edu.place(y=160)

lst = []
lst += "MBA",
lst += "B com",
lst += "Btech",
lst += "Secondry",
lst += "Primary",

varList = StringVar(root)
varList.set("Please Choose                        ")
college = OptionMenu(root,varList,*lst)
college.place(x=296,y=160)

res = Label(root, text = "Resume:", font = "segoe 15")
res.place(y=190)
resume = Entry(root,width = 30)
resume.place(x = 370,y = 195)
resume.insert(30,"No file choosen")
def UploadAction(event=None):
    filename = filedialog.askopenfilename()
    print('Selected:', filename)

button = Button(root, text='Choose file', command=UploadAction)
button.place(x=297,y=195)

adr = Label(root, text = "Address:", font = "segoe 15")
adr.place(y=220)
adr1 = Entry(root,width = 60)
adr1.place(x=300,y=227)
adr1.insert(0,"Address 1")
adr2 = Entry(root,width = 60)
adr2.place(x=300,y=257)
adr2.insert(0,"Address 2")

cnt = []
cnt.append("India")
cnt.append("Japan")
cnt.append("USA")
cnt.append("Sri Lanka")
cnt.append("Australia")
varList = StringVar(root)
varList.set("Select a Country                        ")
co = OptionMenu(root,college,varList,*cnt)
co.place(x=296,y=280)

adr3 = Entry(root,width = 30)
adr3.place(x=300,y=317)
adr3.insert(0,"City")
adr4 = Entry(root,width = 10)
adr4.place(x=495,y=317)
adr4.insert(0,"State")
adr4 = Entry(root,width = 15)
adr4.place(x=570,y=317)
adr4.insert(0,"Zip Code")

phno = Label(root, text = "Phone Number:", font = "segoe 10")
phno.place(y=340)
ph1 = Entry(root,width = 3)
ph1.place(x=300,y=340)
ph2 = Entry(root,width = 40)
ph2.place(x=330,y=340)

hob = Label(root, text = "What are your hobbies:", font = "segoe 10")
hob.place(y=360)
hobby = Entry(root,width = 110)
hobby.place(x=10,y=377)

current_details = Label(root, text = "Precious/Current Employment details",font = "segoe 15",fg="red")
current_details.place(y=400)

cname = Label(root, text = "Company Name:", font = "segoe 15")
cname.place(y=430)
cname1 = Entry(root,width = 60)
cname1.place(x=300,y=437)

jtitle = Label(root, text = "Job Title:", font = "segoe 15")
jtitle.place(y=460)
job = Entry(root,width = 60)
job.place(x=300,y=467)

howlong = Label(root, text = "How long were you here:", font = "segoe 15")
howlong.place(y=490)
timehere = Entry(root,width = 60)
timehere.place(x=300,y=497)

ref1 = Label(root, text = "Reference 1",font = "segoe 15",fg="red")
ref1.place(y=520)

ref1name = Label(root, text = "Name:", font = "segoe 15")
ref1name.place(y=550)
rn1 = Entry(root,width = 60)
rn1.place(x=300,y=557)

ref1phone = Label(root, text = "Phone:", font = "segoe 15")
ref1phone.place(y=580)
rp1 = Entry(root,width = 60)
rp1.place(x=300,y=587)

ref2 = Label(root, text = "Reference 2",font = "segoe 15",fg="red")
ref2.place(y=610)

ref2name = Label(root, text = "Name:", font = "segoe 15")
ref2name.place(y=640)
rn2 = Entry(root,width = 60)
rn2.place(x=300,y=647)

ref2phone = Label(root, text = "Phone:", font = "segoe 15")
ref2phone.place(y=670)
rp2 = Entry(root,width = 60)
rp2.place(x=300,y=677)


button = Button(root, text='Apply',height = 2 ,width=15,bg = "red",fg = "white", command= Add_data)
button.place(x=270,y=710)


root.mainloop()
myConnection.close()

Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\Programming Files\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "<ipython-input-45-3b8dcae95dcd>", line 39, in Add_data
    c.execute('INSERT INTO Data(lname,mail,lst,adr1,college,adr2,adr3,adr4,ph1,ph2,hobby,cname1,job,timehere,rn1,rp1,rn2,rp2) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(l_name,E_mail,my_education,college,Add_1,City,State,ZipCode,phone1,phone2,Hobby,CompanyName,JobTitle,TimeGap,RName1,phone1,Rname2,phone2))
sqlite3.OperationalError: table Data has no column named lname

In [42]:
import sqlite3
myConnection = sqlite3.connect('database.db')

import tkinter as tk
from tkinter import *
root = Tk()
root.geometry("400x250")
limit = myConnection.execute('''SELECT * from Data''')
i = 0
for Data in limit:
    for j in range(len(Data)):
        answer = Entry(root,width = 10,fg = 'red')
        e.grid(row = i,colum = j)
        e.insert(0,Data[j])
    i += 1

root.mainloop()

1
no such table: form

In [ ]:
try:
    myConnection.execute(''' CREATE TABLE IF NOT EXISTS Data(id integer primary key);
    ''')
    myConnection.commit()
    print("Data table successfully created")
except sqlite3.Error as my_error:
  print("error: ",my_error)